import type { Metadata } from 'next'
import Link from 'next/link'
import { Building2, MapPin, Soup, Truck, Utensils } from 'lucide-react'

import { campusToday, getHoursForLocations, getLocations, locationPath, shiftDate } from '@/lib/campus'
import type { Location, LocationHours } from '@/lib/campus'
import { breadcrumbList, canonical } from '@/lib/seo'
import { Breadcrumbs, CampusPage, Card, IconTile, PageHeading } from '@/components/campus/CampusChrome'
import { JsonLd } from '@/components/campus/JsonLd'
import { VenueCard } from '@/components/campus/VenueCard'
import { groupByBuilding } from '@/components/campus/campusDisplay'

/**
 * A day, because the sweep now says when to rebuild.
 *
 * This was five minutes, then an hour, both of them guesses at when `locations` changes — and
 * every guess cost a full ISR write, since the open-now badges put a clock in the output and
 * Vercel only skips the write when the regenerated bytes match. The badges are computed in the
 * browser now (`components/campus/VenueCard.tsx` → `VenueStatus`), so the cached bytes hold
 * only the schedule and change when the 05:00 UTC sweep changes them. `/api/revalidate` is what
 * the sweep calls; the day here is the belt-and-braces fallback for a night the call fails, not
 * the mechanism. `/open-now` remains uncached and is still the to-the-minute answer.
 */
export const revalidate = 86400

const PATH = '/locations'
const TITLE = 'UNC Campus Dining Locations — Every Venue & Building'
const DESCRIPTION =
    'Every UNC Chapel Hill campus dining location, grouped by building: the Chase and Top of Lenoir dining halls, the Bottom of Lenoir and Beach Cafe food courts, department cafes, markets and food trucks — with hours and menus for each.'

export const metadata: Metadata = {
    title: TITLE,
    description: DESCRIPTION,
    keywords: [
        'unc campus dining',
        'unc restaurants',
        'unc campus food',
        'unc food court',
        'bottom of lenoir',
        'unc beach cafe',
        'unc dining locations',
        'food on campus unc',
    ],
    alternates: { canonical: canonical(PATH) },
    openGraph: {
        title: TITLE,
        description: DESCRIPTION,
        url: canonical(PATH),
        siteName: 'Eat UNC',
        type: 'website',
    },
    twitter: { card: 'summary_large_image', title: TITLE, description: DESCRIPTION },
}

const CRUMBS = [
    { name: 'Eat UNC', path: '/' },
    { name: 'Campus Dining Locations', path: PATH },
]

type PageData = { locations: Location[]; hours: LocationHours[]; today: string; failed: boolean }

/**
 * Deliberately not `getOpenNow()`, which is what this page used to call.
 *
 * `getOpenNow` resolves each venue against `new Date()` and hands back who is open at this
 * instant — a clock in the cached output, and therefore a paid ISR write on every one of the
 * 288 regenerations a day this page used to do. The rows themselves are the same query; the
 * badge is now resolved in the browser (`VenueOpenBadge`) so the cached bytes turn over at
 * midnight instead of every five minutes. `/open-now`, whose entire subject is the current
 * instant, still calls `getOpenNow` and is still uncached.
 *
 * Yesterday is in the window because a Late Night period that opened last night can still be
 * running now, and tomorrow because "opens next" after the last venue closes is tomorrow's
 * breakfast — the same reasoning `getOpenNow` documents.
 */
async function loadLocations(): Promise<PageData> {
    const today = campusToday()
    try {
        const locations = await getLocations()
        const hours = await getHoursForLocations(
            locations.map((l) => l.id),
            shiftDate(today, -1),
            shiftDate(today, 1),
        )
        return { locations, hours, today, failed: false }
    } catch {
        return { locations: [], hours: [], today, failed: true }
    }
}

export default async function LocationsIndexPage() {
    const { locations, hours, today, failed } = await loadLocations()

    const hoursByLocation = new Map<string, LocationHours[]>()
    for (const row of hours) {
        const rows = hoursByLocation.get(row.location_id)
        if (rows) rows.push(row)
        else hoursByLocation.set(row.location_id, [row])
    }

    const buildings = groupByBuilding(locations)

    // One entry per destination URL: the four colliding slugs share a page, and the two halls
    // keep their historic /chase and /lenoir URLs.
    const listed = new Map<string, string>()
    for (const location of locations) {
        const path = locationPath(location)
        if (!listed.has(path)) listed.set(path, location.display_label)
    }

    const itemList = {
        '@context': 'https://schema.org',
        '@type': 'ItemList',
        name: 'UNC Chapel Hill campus dining locations',
        description: DESCRIPTION,
        url: canonical(PATH),
        numberOfItems: listed.size,
        itemListOrder: 'https://schema.org/ItemListUnordered',
        itemListElement: Array.from(listed.entries()).map(([path, name], i) => ({
            '@type': 'ListItem',
            position: i + 1,
            name,
            url: canonical(path),
        })),
    }

    return (
        <CampusPage>
            <JsonLd data={itemList} />
            <JsonLd data={breadcrumbList(CRUMBS)} />

            <Breadcrumbs crumbs={CRUMBS} />

            <PageHeading
                icon={<MapPin className="w-6 h-6" />}
                iconClassName="bg-[#4B9CD3]/10 text-[#2c6f9e] dark:text-[#7cc0ec]"
                title="UNC Campus Dining Locations"
                description="Every place UNC Chapel Hill currently serves food, grouped by where it is."
            />

            {failed ? (
                <Card className="p-6">
                    <p className="text-zinc-600 dark:text-zinc-300">
                        The campus location list could not be loaded right now. Try again in a few minutes, or go
                        straight to the <Link href="/hours" className="underline">hours page</Link>.
                    </p>
                </Card>
            ) : (
                <>
                    {buildings.map((group) => {
                        const Icon =
                            group.venueGroup === 'Food Trucks'
                                ? Truck
                                : group.items.some((l) => l.kind === 'dining_hall')
                                  ? Utensils
                                  : group.items.length > 2
                                    ? Soup
                                    : Building2

                        return (
                            <section
                                key={group.venueGroup}
                                id={group.venueGroup.toLowerCase().replace(/[^a-z0-9]+/g, '-')}
                                className="mb-10 scroll-mt-8"
                            >
                                <div className="flex items-start gap-3 mb-3">
                                    <IconTile>
                                        <Icon className="w-5 h-5" />
                                    </IconTile>
                                    <div>
                                        {/*
                                            `short`, not `heading`. The long form ("Chase Hall —
                                            Chase Dining Hall, Cafe 1789 & Rams Market") was
                                            written to introduce a section of prose; with the
                                            prose gone it just repeats the venue names listed
                                            directly underneath it.
                                        */}
                                        <h2 className="text-xl sm:text-2xl font-bold tracking-tight text-zinc-900 dark:text-zinc-50">
                                            {group.meta.short}
                                        </h2>
                                        <p className="text-sm text-zinc-500 dark:text-zinc-400">
                                            {group.items.length} {group.items.length === 1 ? 'venue' : 'venues'}
                                        </p>
                                    </div>
                                </div>

                                <div className="grid sm:grid-cols-2 gap-3">
                                    {group.items.map((location) => (
                                        <VenueCard
                                            key={location.id}
                                            location={location}
                                            rows={hoursByLocation.get(location.id) ?? []}
                                            today={today}
                                        />
                                    ))}
                                </div>
                            </section>
                        )
                    })}

                </>
            )}
        </CampusPage>
    )
}
