import { revalidatePath } from 'next/cache'
import { timingSafeEqual } from 'node:crypto'

/**
 * Rebuild the cached campus pages once, when the data behind them actually changes.
 *
 * `eat-unc-backend`'s 05:00 UTC sweep is the only thing that writes `locations`,
 * `location_hours`, `menus` or `external_*`. Everything this route touches was previously on a
 * 5- or 15-minute timer instead, guessing at that moment ~29,000 times a day across 38
 * prerendered venue paths — and paying an ISR write for every guess, because Vercel only skips
 * the write when the regenerated bytes match the previous copy and the pages had a clock in
 * them. De-clocking the output (see `components/campus/VenueStatus.tsx`) is what makes this
 * route possible; this route is what makes the de-clocking worth doing.
 *
 * Called from the last step of `.github/workflows/daily_locations.yml`. Safe to call by hand,
 * and safe to call twice: a revalidation whose output is unchanged costs nothing.
 */
export const dynamic = 'force-dynamic'

/**
 * `'page'` revalidates every already-cached path under a dynamic segment, which is the only way
 * to reach all 38 venues without enumerating them — and enumerating them would mean querying
 * Supabase from a route whose whole job is to avoid work.
 */
const PATHS: Array<[path: string, type: 'page' | 'layout']> = [
    ['/locations', 'page'],
    ['/locations/[slug]', 'page'],
    ['/brands', 'page'],
    ['/brands/[slug]', 'page'],
    ['/hours', 'page'],
    ['/today', 'page'],
    ['/sitemap.xml', 'page'],
]

/**
 * Constant-time, and length-safe: `timingSafeEqual` throws rather than returns false when the
 * buffers differ in length, which would turn a wrong-length token into a 500 and leak the
 * expected length through the status code.
 */
function tokenMatches(presented: string, expected: string): boolean {
    const a = Buffer.from(presented)
    const b = Buffer.from(expected)
    return a.length === b.length && timingSafeEqual(a, b)
}

export async function POST(request: Request): Promise<Response> {
    const expected = process.env.REVALIDATE_TOKEN

    // Fails closed. An unset token must not mean "anyone may spend the ISR write allowance" —
    // that is the resource this whole change exists to conserve.
    if (!expected) {
        return Response.json({ error: 'REVALIDATE_TOKEN is not configured' }, { status: 503 })
    }

    const presented = request.headers.get('authorization')?.replace(/^Bearer /, '') ?? ''
    if (!tokenMatches(presented, expected)) {
        return Response.json({ error: 'Unauthorized' }, { status: 401 })
    }

    for (const [path, type] of PATHS) {
        revalidatePath(path, type)
    }

    return Response.json({
        revalidated: PATHS.map(([path]) => path),
        at: new Date().toISOString(),
    })
}

/** A GET would be cached and crawled; the sweep posts. */
export async function GET(): Promise<Response> {
    return Response.json({ error: 'Method not allowed — POST with a bearer token' }, { status: 405 })
}
